import type { Metadata } from 'next'
import '@/styles/globals.css'
import '@/styles/theme.css'

import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function HomePageLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {

    return (
        <>
            <Header />
            {children}
            <Footer />
        </>
    )
}
