import type { Metadata } from 'next'
import '@/styles/globals.css'
import '@/styles/theme.css'
import { ToastContainer } from "react-toastify";

import { Geist, Geist_Mono } from 'next/font/google'

import { HeroUIProviders } from './HeroUIProvider'
import Header from '@/components/Layout/Header'
import Footer from '@/components/Layout/Footer'
import GlobalContexrProvider from "./GlobalContexrProvider";

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {

    return (
        <html lang="en">
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-full`}>
                <ToastContainer autoClose={2000} />
                <HeroUIProviders>
                    <GlobalContexrProvider>
                        {children}
                    </GlobalContexrProvider>
                </HeroUIProviders>
            </body>
        </html>
    )
}
